### ISSUE TITLE
Transactions not working

### ISSUE THREAD

**Issue by joaolucas89** [postmanlabs/sails-mysql-transactions#36] opened 2016-03-20 01:40 UTC
Sometimes the field "transactionId" is not injected in the tables and the transactions do not work. I wonder why.
Thank you.

**Comment by shamasis** [comment] 2016-03-22 11:35
@joaolucas89 - this could happen if there is no value or criteria object to "carry forward" the transaction id. This is super rare. However, I am working on making this work without transactionId in database at all. It is already done for the `.count` function... need to put time to do it for all other methods.

**Comment by shamasis** [comment] 2016-03-22 11:36
Marking this as duplicate of #1

**Closed by shamasis** 2016-03-22 11:36 UTC
Labels: bug, duplicate, enhancement
